name: MATLAB Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v6

      - name: 1st Run of testSecretAPIs script
        uses: matlab-actions/run-command@v3
        with:
          command: testSecretAPIs;

      - name: 2nd Run of testSecretAPIs script
        uses: matlab-actions/run-command@v3
        with:
          command: testSecretAPIs;
