name: MATLAB Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4

      - name: Run personalValue script (with setting)
        uses: matlab-actions/run-command@v3
        with:
          command: |
            disp('Checking if PersonalValue of MATLAB settings persist in CICD!');
            s = settings();
            s.matlab.commandwindow.NumericFormat.PersonalValue = 'long';
            personalValue;

      - name: Run script
        uses: matlab-actions/run-command@v3
        with:
          command: personalValue
