name: MATLAB Build

on:
  # push:
  #   branches: [ main ]
  # pull_request:
  #   branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: [self-hosted, matlab-r2026a]
    env:
        MW_START_MSH_IN_BATCH: 1
    steps:
      - uses: actions/checkout@v6

      - name: Runner info
        run: |
          echo Runner: ${{ runner.name }}
          echo OS: ${{ runner.os }}

      - name: 1st Run of testSecretAPIs script
        uses: matlab-actions/run-command@v3
        with:
          command: system('where matlab')
          
      # - name: 2nd Run of testSecretAPIs script
      #   uses: matlab-actions/run-command@v3
      #   with:
      #     command: testSecretAPIs;
